ktor:
  deployment:
    host: 0.0.0.0
    port: 8080
  application:
    modules:
      - faq.fastreport.ru.module
postgres:
  jdbcURL: "jdbc:postgresql://db:5432/frFaq"
  user: "frFaqService"
  password: "yc6t23746ch7t436x"