services:
  db:
    build:
      context: ./Docker/db/
      dockerfile: db.Dockerfile
    platform: linux/amd64
    ports:
      - "5432:5432"
    restart: always
    container_name: fr-faq-db
    volumes:
      - pg-volume:/var/lib/postgresql/data
    env_file:
      - frFaq.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -d fr_faq_db -U frFaqService" ]
      interval: 3s
  flyway:
    container_name: fr-flyway
    environment:
      - FLYWAY_USER=frFaqService
      - FLYWAY_PASSWORD=yc6t23746ch7t436x
      - FLYWAY_URL=jdbc:postgresql://host.docker.internal:5432/fr_faq_db
      - FLYWAY_GROUP=true
    image: flyway/flyway:latest
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - $PWD/migrations:/flyway/sql
    depends_on:
      db:
        condition: service_healthy
  web:
    build: .
    container_name: fr-faq-service
    platform: linux/amd64
    network_mode: bridge
    restart: always
    env_file:
      - frFaq.env
    ports:
      - "8080:8080"
    depends_on:
      - flyway
volumes:
  pg-volume: { }